### ISSUE TITLE
Add an output example to the README

### ISSUE THREAD

**Issue by EcksDy** [manzurola/align-arr#4]
Heya, 
great job on the library! :) 

Currently I needed to look into the source code/install the package and run it myself to understand the implementation.

I think it will be a lot easier to understand how and what the lib does if there's a more elaborate example section in the readme.
I'd love to see the output of the usage(`Edit<number>[]`) and maybe some explanations around it.

**Comment by manzurola** [comment]
Hey @EcksDy , thanks for this great input!

I've added outputs and more to the docs, and officially released version 1.0.0.

Happy to hear your thoughts :)

**Comment by manzurola** [comment]
@EcksDy closing this, stay in touch ❤️
